on:
  push:
    branches:
    - master

jobs:
  run-commands:
      runs-on: ubuntu-latest
      steps:
      - name: Remote SSH Commands
        # You may pin to the exact commit or the version.
        # uses: fifsky/ssh-action@58b3c484be9c20cf118fd3b939a6d2cb3c769512
        uses: fifsky/ssh-action@v0.0.6
        with:
          # Command to execute on the remote server.
          command: ls -la  
          # Hostname or IP address of the server.
          host: 94.130.79.150
          # optional, default is localhost
          # Username for authentication.
          #user: # optional, default is root
          # Port number of the server.
          #port: # optional, default is 22
          # String that contains a private key for either key-based or hostbased user authentication (OpenSSH format)
          key: ${{secrets.SECRET_KEY}}# optional
          # File location to an identity file
          #keyfile: # optional
          # Password for authentication.
          #pass: # optional
          # SSH parameters for example: -tt.
          #args: # optional


